name: ecommerce_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2 # for state management and context less stuff
  flutter_screenutil: ^5.9.3 # make app responsive
  shared_preferences: ^2.5.3 # shared preferences persistence key value store
  http: ^1.2.2
  flutter_launcher_icons: ^0.14.4 # change app icon
  change_app_package_name: ^1.5.0 # change package name
  rename_app: ^1.6.5 # rename app
  flutter_svg: ^2.2.1 # for svg icons
  flutter_animate: ^4.5.2 # for animation
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.4

dev_dependencies:
  mockito: ^5.5.1
  flutter_lints: ^6.0.0

  integration_test:
    sdk: flutter

  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/vectors/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
